
# Startup Programs
exec-once = swww-daemon | swww img Pictures/bg1.jpeg
exec-once = systemctl --user start hyprpolkitagent
exec-once = wal -R
exec-once = fcitx5
exec-once = easyeffects
exec-once = hyprsunset
exec-once = waybar

# Programs
$terminal = kitty
$fileManager = thunar
$menu = hyprlauncher
$browser = zen-browser
$launcher = ~/.config/rofi/launchers/type-2/launcher.sh
$notification = swaync-client -t
$lock = hyprlock
